server:
  port: 8083
  servlet:
    context-path: /ordering

spring:
  application:
    name: ordering-service
  datasource:
    url: "jdbc:mysql://localhost:3306/ordering-ecommer-car"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/anhqui

cloudinary:
  cloud-name: do43r8nr0
  api-key: 947875495844325
  api-secret: evQEPk5TbxIMpCWbbXl8sLMbo6A

idp:
  url: http://localhost:8180
  client-id: ecommer-app
  client-secret: 2anScggPiIAmbA5mW5SI5JnGZAcCVveo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    prefer-ip-address: true

logging:
  level:
    org.springframework.security.web: DEBUG
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
