eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

idp:
  url: http://keycloak:8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/anhqui
  rabbitmq:
    host: rabbitmq

app:
  services:
    identity:
      url: http://identity-service:8081
    catalog:
      url: http://catalog-service:8082
    payment:
      url: http://payment-service:8084
