server:
  port: 8085
  servlet:
    context-path: /chat

spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat-service
      auto-index-creation: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/anhqui

app:
  services:
    main:
      url: http://localhost:8080/ecommer-car-web

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

idp:
  url: http://localhost:8180/realms/anhqui/protocol/openid-connect/token
  client-id: ecommer-app
  client-secret: 2anScggPiIAmbA5mW5SI5JnGZAcCVveo
