server:
  port: 8082
  servlet:
    context-path: /chat

spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/chat-service
      auto-index-creation: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/anhqui

app:
  services:
    main:
      url: http://localhost:8080/ecommer-car-web

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

idp:
  url: http://localhost:8180/realms/anhqui/protocol/openid-connect/token
  client-id: ecommer_app
  client-secret: WKnFf5PHkolShqwY8CnVrYP7bHhYph4H


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: loan-service
  tracing:
    sampling:
      probability: 1.0