server:
  port: 8085
  servlet:
    context-path: /chat

spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://root:123456@localhost:27017/chat-service?authSource=admin}
      auto-index-creation: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/anhqui

app:
  services:
    identity:
      url: ${IDENTITY_SERVICE_URL:http://localhost:8081}
    catalog:
      url: ${CATALOG_SERVICE_URL:http://localhost:8082}
    ordering:
      url: ${ORDERING_SERVICE_URL:http://localhost:8083}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:localhost}

idp:
  url: ${KEYCLOAK_URL:http://localhost:8180}/realms/anhqui/protocol/openid-connect/token
  client-id: ${KEYCLOAK_CLIENT_ID:ecommer-app}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:2anScggPiIAmbA5mW5SI5JnGZAcCVveo}
