server:
  port: 8080
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service
  datasource:
    url: "jdbc:mysql://localhost:3306/ecommercar"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true