server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: main-service
              uri: http://localhost:8080
              predicates:
                - Path=${app.api-prefix}/ecommer-car-web/**
              filters:
                - StripPrefix=2
            - id: notification-service
              uri: http://localhost:8081
              predicates:
                - Path=${app.api-prefix}/notification/**
              filters:
                - StripPrefix=2
            - id: payment-service
              uri: http://localhost:8083
              predicates:
                - Path=${app.api-prefix}/payment/**
              filters:
                - StripPrefix=2

idp:
  url: http://localhost:8180
  client-id: ecommer_app
  client-secret: z9CS4HlptoirirLWCOcsS9wj3T11l9Y3


management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  observations:
    key-values:
      application: loan-service
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.security.web: DEBUG
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"