server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: main-service
              uri: http://localhost:8080
              predicates:
                - Path=${app.api-prefix}/auth/**
              filters:
                - StripPrefix=2
            - id: notification-service
              uri: http://localhost:8082
              predicates:
                - Path=${app.api-prefix}/notification/**
              filters:
                - StripPrefix=2
