server:
  port: 8888

app:
  api-prefix: /api/v1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=${app.api-prefix}/auth/**
          filters:
            - StripPrefix=2

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=${app.api-prefix}/chat/**
          filters:
            - StripPrefix=2

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=${app.api-prefix}/payment/**
          filters:
            - StripPrefix=2

        - id: ordering-service
          uri: lb://ordering-service
          predicates:
            - Path=${app.api-prefix}/ordering/**
          filters:
            - StripPrefix=2

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=${app.api-prefix}/catalog/**
          filters:
            - StripPrefix=2

        - id: cms-service
          uri: lb://cms-service
          predicates:
            - Path=${app.api-prefix}/cms/**
          filters:
            - StripPrefix=2



idp:
  url: http://localhost:8180
  client-id: ecommer-app
  client-secret: 2anScggPiIAmbA5mW5SI5JnGZAcCVveo

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health, info, metrics, prometheus
#  metrics:
#    distribution:
#      percentiles-histogram:
#        http:
#          server:
#            requests: true
#  observations:
#    key-values:
#      application: loan-service
#  tracing:
#    sampling:
#      probability: 1.0

logging:
  level:
    org.springframework.security.web: DEBUG
#  pattern:
#    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"