server:
  port: 8888

app:
  application:
    name: api-gateway
  api-prefix: /api/v1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:localhost}

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=${app.api-prefix}/catalog/**
          filters:
            - StripPrefix=2

        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=${app.api-prefix}/chat/**
          filters:
            - StripPrefix=2

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=${app.api-prefix}/payment/**
          filters:
            - StripPrefix=2

        - id: ordering-service
          uri: lb://ordering-service
          predicates:
            - Path=${app.api-prefix}/ordering/**
          filters:
            - StripPrefix=2

        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=${app.api-prefix}/ai/**
          filters:
            - StripPrefix=3

idp:
  url: ${KEYCLOAK_URL:http://localhost:8180}
  client-id: ${KEYCLOAK_CLIENT_ID:ecommer-app}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:lVaXmGMg3bmpkAcDSvBcqhiu1QSEiUGG}

app:
  base-url: ${FRONTEND_URL:http://localhost:3000}



logging:
  level:
    org.springframework.security.web: DEBUG