server:
    port: 8080
    tomcat:
        max-swallow-size: 50MB
        max-part-count: 30
    servlet:
        context-path: /ecommer-car-web

spring:
    servlet:
        multipart:
            enabled: true
            resolve-lazily: false
            max-file-size: 10MB
            max-request-size: 200MB
    application:
        name: main-service
    datasource:
        url: "jdbc:mysql://localhost:3306/ecommercar"
        driverClassName: "com.mysql.cj.jdbc.Driver"
        username: root
        password: 12345678
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    kafka:
        bootstrap-servers: localhost:9094
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8180/realms/anhqui


management:
    endpoints:
        web:
            exposure:
                include: health, info, metrics, prometheus
    metrics:
        distribution:
            percentiles-histogram:
                http:
                    server:
                        requests: true
    observations:
        key-values:
            application: loan-service
    tracing:
        sampling:
            probability: 1.0

cloudinary:
    cloud-name: do43r8nr0
    api-key: 947875495844325
    api-secret: evQEPk5TbxIMpCWbbXl8sLMbo6A


idp:
    url: http://localhost:8180
    client-id: ecommer_app
    client-secret: z9CS4HlptoirirLWCOcsS9wj3T11l9Y3



logging:
    level:
        org.springframework.security.web: DEBUG
    pattern:
        correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

