server:
    port: 8080
    servlet:
        context-path: /auth

spring:
    application:
        name: main-service
    datasource:
        url: "jdbc:mysql://localhost:3306/ecommercar"
        driverClassName: "com.mysql.cj.jdbc.Driver"
        username: root
        password: 12345678
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

    kafka:
        bootstrap-servers: localhost:9094
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8180/realms/anhqui



cloudinary:
    cloud-name: do43r8nr0
    api-key: 947875495844325
    api-secret: evQEPk5TbxIMpCWbbXl8sLMbo6A

#jwt:
#    signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
#    valid-duration: 3600
#    refreshable-duration: 36000

idp:
    url: http://localhost:8180
    client-id: ecommer_app
    client-secret: z9CS4HlptoirirLWCOcsS9wj3T11l9Y3

logging:
    level:
        org.springframework.security.web: DEBUG

