server:
  port: 8084
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service
  datasource:
    url: "jdbc:mysql://localhost:3306/payment-ecommer-car"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/anhqui

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123456

app:
  base-url: http://localhost:8888
  frontend-url: http://localhost:3000
  services:
    identity:
      url: http://localhost:8081
    catalog:
      url: http://localhost:8082
    ordering:
      url: http://localhost:8083


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    prefer-ip-address: true


payment:
  vnpay:
    tmn-code: GSCN06EN
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: ${app.base-url}/api/v1/payment/payments/vnpay-callback
    hash-secret: ZR2XBKVYB88L0IGB8P0RR9ZDOBOH5HH5
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html


idp:
  url: http://localhost:8180/realms/anhqui/protocol/openid-connect/token
  client-id: ecommer-app
  client-secret: lVaXmGMg3bmpkAcDSvBcqhiu1QSEiUGG
