server:
  port: 8084
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQL_HOST:localhost}:3306/payment-ecommer-car}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:12345678}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://${PUBLIC_IP:localhost}:8180}/realms/anhqui

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

app:
  base-url: ${API_GATEWAY_URL:http://${PUBLIC_IP:localhost}:8888}
  frontend-url: ${FRONTEND_URL:http://${PUBLIC_IP:localhost}:3000}
  services:
    identity:
      url: ${IDENTITY_SERVICE_URL:http://${PUBLIC_IP:localhost}:8081}
    catalog:
      url: ${CATALOG_SERVICE_URL:http://${PUBLIC_IP:localhost}:8082}
    ordering:
      url: ${ORDERING_SERVICE_URL:http://${PUBLIC_IP:localhost}:8083}


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://${PUBLIC_IP:localhost}:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    prefer-ip-address: true


payment:
  vnpay:
    tmn-code: GSCN06EN
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: ${app.base-url}/api/v1/payment/payments/vnpay-callback
    hash-secret: ZR2XBKVYB88L0IGB8P0RR9ZDOBOH5HH5
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html


idp:
  url: ${KEYCLOAK_URL:http://${PUBLIC_IP:localhost}:8180}/realms/anhqui/protocol/openid-connect/token
  client-id: ${KEYCLOAK_CLIENT_ID:ecommer-app}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:lVaXmGMg3bmpkAcDSvBcqhiu1QSEiUGG}
