server:
  port: 8083
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service
  datasource:
    url: "jdbc:mysql://localhost:3306/payment_ecommer"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/anhqui

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 123456

app:
  services:
    main:
      url: http://localhost:8080/ecommer-car-web


payment:
  vnpay:
    tmn-code: BSYVAKDJ
    init-payment-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: http://localhost:8888/api/v1/payment/checkout/vnpay_ipn
    secret-key: LDELTSZERUCS745OLFK8OJI1X1JGFI5L
    time-out: 10

resilience4j:
  circuitbreaker:
    instances:
      vnpayCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
  retry:
    instances:
      vnpayRetry:
        maxAttempts: 3
        waitDuration: 2s
  timelimiter:
    instances:
      vnpayTimeLimiter:
        timeoutDuration: 5s
