server:
    port: 8081
    servlet:
        context-path: /notification
spring:
    application:
        name: notification-service

    kafka:
        bootstrap-servers: localhost:9094
        consumer:
            group-id: notification-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
                spring.json.trusted.packages: com.tlaq.event.dto
                spring.json.value.default.type: com.tlaq.event.dto.NotificationEvent


    send-grid:
        api-key: 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
        from-email: anhqui04062004@gmail.com
        from-name: ecommer_car

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8180/realms/anhqui

#management:
#    endpoints:
#        web:
#            exposure:
#                include: health, info, metrics, prometheus
#    metrics:
#        distribution:
#            percentiles-histogram:
#                http:
#                    server:
#                        requests: true
#    observations:
#        key-values:
#            application: loan-service
#    tracing:
#        sampling:
#            probability: 1.0

logging:
    level:
        org.springframework.security.web: DEBUG
#    pattern:
#        correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"