server:
    port: 8088
    servlet:
        context-path: /notification
spring:
    application:
        name: notification-service

    rabbitmq:
      host: ${RABBITMQ_HOST:localhost}
      port: ${RABBITMQ_PORT:5672}
      username: ${RABBITMQ_USERNAME:root}
      password: ${RABBITMQ_PASSWORD:123456}

    send-grid:
        api-key: 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
        from-email: anhqui04062004@gmail.com
        from-name: ecommer_car

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/anhqui

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:localhost}

idp:
  url: ${KEYCLOAK_URL:http://localhost:8180}
  client-id: ${KEYCLOAK_CLIENT_ID:ecommer-app}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:lVaXmGMg3bmpkAcDSvBcqhiu1QSEiUGG}


logging:
    level:
        org.springframework.security.web: DEBUG
