server:
    port: 8088
    servlet:
        context-path: /notification
spring:
    application:
        name: notification-service

    rabbitmq:
      host: localhost
      port: 5672
      username: root
      password: 123456

    send-grid:
        api-key: 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
        from-email: anhqui04062004@gmail.com
        from-name: ecommer_car

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8180/realms/anhqui

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

idp:
  url: http://localhost:8180
  client-id: ecommer-app
  client-secret: lVaXmGMg3bmpkAcDSvBcqhiu1QSEiUGG


logging:
    level:
        org.springframework.security.web: DEBUG
