server:
    port: 8082
    servlet:
        context-path: /notification
spring:
    application:
        name: notification-service
#    data:
#        mongodb:
#            uri: mongodb://root:root@localhost:27017/notification-service?authSource=admin
    kafka:
        bootstrap-servers: localhost:9094
        consumer:
            group-id: notification-group
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
                spring.json.trusted.packages: com.tlaq.event.dto
                spring.json.value.default.type: com.tlaq.event.dto.NotificationEvent


    send_grid:
        api_key: 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
        from_email: anhqui04062004@gmail.com
        from_name: ecommer_car