server:
    port: 8088
    servlet:
        context-path: /notification
spring:
    application:
        name: notification-service
    config:
        import:
            - optional:file:.env
            - optional:file:../.env
    data:
        mongodb:
          uri: ${MONGODB_URI}/notification-service?authSource=admin


    rabbitmq:
      host: ${RABBITMQ_HOST:localhost}
      port: ${RABBITMQ_PORT:5672}
      username: ${RABBITMQ_USERNAME}
      password: ${RABBITMQ_PASSWORD}

    send-grid:
        api-key: ${SENDGRID_API_KEY}
        from-email: ${SENDGRID_FROM_EMAIL:anhqui04062004@gmail.com}
        from-name: ${SENDGRID_FROM_NAME:ecommer_car}

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_URL:http://${PUBLIC_IP:localhost}:8180}/realms/anhqui

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://${PUBLIC_IP:localhost}:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_HOSTNAME:localhost}

idp:
  url: ${KEYCLOAK_URL:http://${PUBLIC_IP:localhost}:8180}
  client-id: ${KEYCLOAK_CLIENT_ID:ecommer-app}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}


logging:
    level:
        org.springframework.security.web: DEBUG
