server:
    port: 8080
    servlet:
        context-path: /auth

spring:
    application:
        name: auth-service
    datasource:
        url: "jdbc:mysql://localhost:3306/ecommercar"
        driverClassName: "com.mysql.cj.jdbc.Driver"
        username: root
        password: 12345678
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

cloudinary:
    cloud-name: do43r8nr0
    api-key: 947875495844325
    api-secret: evQEPk5TbxIMpCWbbXl8sLMbo6A

jwt:
    signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
    valid-duration: 3600 # in second
    refreshable-duration: 36000 # in seconds

logging:
    level:
        org.springframework.security.web: DEBUG

