name: Java Microservices CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'EcommerWebCar/api-gateway/**'
      - 'EcommerWebCar/catalog-service/**'
      - 'EcommerWebCar/chat-service/**'
      - 'EcommerWebCar/config-server/**'
      - 'EcommerWebCar/eureka-server/**'
      - 'EcommerWebCar/fraud-detection-service/**'
      - 'EcommerWebCar/identity-service/**'
      - 'EcommerWebCar/notification-service/**'
      - 'EcommerWebCar/ordering-service/**'
      - 'EcommerWebCar/payment-service/**'
      - '.github/workflows/java-services-ci.yml'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: 
          - api-gateway
          - catalog-service
          - chat-service
          - config-server
          - eureka-server
          - fraud-detection-service
          - identity-service
          - notification-service
          - ordering-service
          - payment-service
      fail-fast: false

    defaults:
      run:
        working-directory: EcommerWebCar/${{ matrix.service }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        if [ -f pom.xml ]; then
          mvn -B package --file pom.xml -DskipTests
        else
          echo "Skipping Maven build... No pom.xml found"
        fi

    - name: Build Docker Image
      run: |
        if [ -f Dockerfile ]; then
          docker build -t ${{ matrix.service }}:latest .
        else
          echo "Skipping Docker build... No Dockerfile found"
        fi
